from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('sales/', views.sales_list, name='sales_list'),
    path('sales/add/', views.sales_add, name='sales_add'),
    path('sales/<int:pk>/edit/', views.sales_edit, name='sales_edit'),
    path('sales/<int:pk>/delete/', views.sales_delete, name='sales_delete'),
    path('companies/', views.company_list, name='company_list'),
    path('members/', views.team_member_list, name='team_member_list'),
    path('members/add/', views.team_member_add, name='team_member_add'),
    path('members/<int:pk>/edit/', views.team_member_edit, name='team_member_edit'),
    path('members/<int:pk>/delete/', views.team_member_delete, name='team_member_delete'),
    path('teams/', views.team_list, name='team_list'),
    path('teams/add/', views.team_add, name='team_add'),
    path('teams/<int:pk>/edit/', views.team_edit, name='team_edit'),
    path('teams/<int:pk>/delete/', views.team_delete, name='team_delete'),
    path('departments/', views.department_list, name='department_list'),
    path('departments/add/', views.department_add, name='department_add'),
    path('departments/<int:pk>/edit/', views.department_edit, name='department_edit'),
    path('departments/<int:pk>/delete/', views.department_delete, name='department_delete'),
    path('export/', views.export_excel, name='export_excel'),
    path('sales/bulk-upload/', views.sales_bulk_upload, name='sales_bulk_upload'),
    path('sales/template/', views.sales_template_download, name='sales_template_download'),
    path('login-logs/', views.login_log_list, name='login_log_list'),
    path('duplicates/', views.duplicate_companies, name='duplicate_companies'),
    path('duplicates/delete/', views.duplicate_companies_delete, name='duplicate_companies_delete'),
    path('duplicates/link/', views.duplicate_companies_link, name='duplicate_companies_link'),
    path('api/team-members/', views.get_team_members, name='get_team_members'),
    path('change-password/', views.change_password, name='change_password'),
    path('users/', views.user_list, name='user_list'),
    path('users/add/', views.user_add, name='user_add'),
    path('users/<int:pk>/edit/', views.user_edit, name='user_edit'),
    path('users/<int:pk>/delete/', views.user_delete, name='user_delete'),
    path('users/<int:pk>/change-password/', views.user_change_password, name='user_change_password'),
]

