# Generated by Django 4.2.7 on 2025-11-17 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='사업부명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '사업부',
                'verbose_name_plural': '사업부',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='팀명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.department', verbose_name='사업부')),
            ],
            options={
                'verbose_name': '팀',
                'verbose_name_plural': '팀',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.team', verbose_name='팀')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자 계정')),
            ],
            options={
                'verbose_name': '팀원',
                'verbose_name_plural': '팀원',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContractCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='업체명')),
                ('representative', models.CharField(max_length=100, verbose_name='대표자명')),
                ('phone', models.CharField(max_length=20, verbose_name='전화번호')),
                ('contract_date', models.DateField(verbose_name='계약일')),
                ('contract_expiry', models.DateField(verbose_name='계약만료일')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='결제금액')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.team', verbose_name='담당 팀')),
                ('team_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.teammember', verbose_name='담당 팀원')),
            ],
            options={
                'verbose_name': '계약업체',
                'verbose_name_plural': '계약업체',
                'ordering': ['-contract_date'],
            },
        ),
    ]
