# Generated by Django 4.2.7 on 2025-11-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractcompany',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='contractcompany',
            name='representative',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='대표자명'),
        ),
    ]
