# Generated by Django 4.2.7 on 2025-11-19 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm_app', '0002_alter_contractcompany_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='아이디')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='사용자 에이전트')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='로그인 시간')),
                ('success', models.BooleanField(default=True, verbose_name='로그인 성공')),
                ('failure_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='실패 사유')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '로그인 로그',
                'verbose_name_plural': '로그인 로그',
                'ordering': ['-login_time'],
            },
        ),
    ]
